services:
  postgres:
    container_name: postgres-sql-wac
    image: postgres:15

    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: whatsapp_clone

    ports:
      - "5432:5432"

    volumes:
      - postgres:/var/lib/postgresql/data

    networks:
      - whatsapp_clone

    restart: unless-stopped


  keycloak:
    container_name: keycloak-wac
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # --- connect to postgres
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/whatsapp_clone
      KC_DB_USERNAME: username
      KC_DB_PASSWORD: password

    depends_on:
      - postgres

    networks:
      - whatsapp_clone

    command:
      - "start-dev"
    restart: unless-stopped

volumes:
  postgres:
    driver: local

networks:
  whatsapp_clone:
    driver: bridge





